#!/bin/sh
# Set up a virtual environment with the required tools, build, and deploy the docs.
#
# Run from the root directory of the project as
# .github/scripts/docs-build-deploy prerelease main
# All arguments after the first are passed to `mike deploy`, run
# `uv run -- mike deploy --help` for options. Note that `mike deploy`
# creates a commit directly on the `gh-pages` branch.
set -ev

version="${1:?missing version argument}"
commit_hash="$(git rev-parse @ | cut -c -12)"

cd "$(git rev-parse --show-toplevel)/web/docs"

# TODO: remove jj/ prefix before merge
npm run build -- --base "/jj/$version/"

git checkout gh-pages
rm -rf "$version"
mv web/docs/dist "$version"
git add "$version"

# TODO: update versions.json

if test "$version" = "prerelease" ; then
    commit_msg="Deploy prerelease docs for $commit_hash"
else
    commit_msg="Deploy docs for $version"
fi

git commit -m "$commit_msg" || echo "No changes to commit"
git push origin gh-pages
