#!/bin/sh
#
# Builds the documentation website, commits and pushes it to the gh-pages
# bookmark. The first argument is the name of the version. If the version
# is "prerelease", only that is updated. If the version is anything else
# (presumably vX.Y.Z for a new release), the "latest" alias is also updated and
# the new version is recorded in `versions.json` for the version switcher.
#
set -ev

version="${1:?missing version argument}"
commit_hash="$(git rev-parse @ | cut -c -12)"
repo_root="$(git rev-parse --show-toplevel)"

build_site() {
    site="${1:?missing site argument}"

    cd "$repo_root/web/docs"
    npm run build -- --base "/$site/"
    cd "$repo_root"

    # move to $site-staging to avoid conflict with existing site
    # (e.g. "prerelease" or "latest") when checking out gh-pages
    mv web/docs/dist "$site-staging"
}

git_add_site() {
    site="${1:?missing site argument}"

    rm -rf "$site"
    mv "$site-staging" "$site"
    git add "$site"
}

if test "$version" = "prerelease" ; then
    build_site "$version"

    git checkout gh-pages
    git_add_site "$version"

    commit_msg="Deploy prerelease docs for $commit_hash"
else
    build_site "$version"
    # Build the "latest" alias from scratch. Copying over the site of the
    # explicit version doesn't work, because links from the "latest" site would
    # point to the explicit version site.
    build_site "latest"

    git checkout gh-pages
    git_add_site "$version"
    git_add_site "latest"

    # update data for version selector:
    # - remove "latest" alias from previous version
    # - add new version with "latest" alias
    cat versions.json \
        | jq 'map(.aliases |= map(select(. != "latest")))' versions.json \
        | jq --arg version "$version" '. = (.[:1] + [{
            "version": $version,
            "title": $version,
            "aliases": ["latest"]
        }] + .[1:])' > versions-staging.json
    mv versions-staging.json versions.json
    git add versions.json

    commit_msg="Deploy docs for $version"
fi

git commit -m "$commit_msg" || echo "No changes to commit"
git push origin gh-pages
