name: website

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  prerelease-docs-build-deploy:
    if: github.repository_owner == 'jj-vcs' # Stops this job from running on forks
    # IMPORTANT: this workflow also functions as a test for `docs-deploy-website-latest-release` in
    # releases.yml. Any fixes here should probably be duplicated there.
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          # `.github/scripts/docs-build-deploy` will need to `git push` to the gh-pages branch
          persist-credentials: true
      - run: git fetch origin gh-pages --depth=1
      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: '22'
          package-manager-cache: false
      - name: Install dependencies
        working-directory: web
        run: npm ci
      - name: Compile and deploy docs to the "prerelease" section of the website
        run: |
          git config user.name 'jj-docs[bot]'
          git config user.email 'jj-docs[bot]@users.noreply.github.io'
          .github/scripts/docs-build-deploy "prerelease"
      - name: "Show `git diff --stat`"
        run: git diff --stat gh-pages^ gh-pages || echo "(No diffs)"
