name: website

on:
  push:
    branches:
      - main

permissions: {}

jobs:
  prerelease-docs-build-deploy:
    permissions:
      contents: write
    # TODO: I enabled this job on my own fork for testing. Uncomment before merge.
    # if: github.repository_owner == 'jj-vcs' # Stops this job from running on forks
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          persist-credentials: true
      - run: "git fetch origin gh-pages --depth=1"
      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020
        with:
          node-version: '22'
      - name: Install dependencies
        working-directory: web/docs
        run: npm ci
      - name: Build Starlight docs
        working-directory: web/docs
        run: npm run build -- --base /jj/prerelease/ # TODO: remove jj/ prefix before merge
      - name: Deploy to gh-pages/starlight
        run: |
          commit_hash="$(git rev-parse @ | cut -c -12)"
          git config user.name 'jj-docs[bot]'
          git config user.email 'jj-docs[bot]@users.noreply.github.io'
          git checkout gh-pages
          rm -rf prerelease
          mv web/docs/dist prerelease
          git add prerelease
          git commit -m "Deploy prerelease docs for $commit_hash" || echo "No changes to commit"
          git push origin gh-pages
